config/routes.rb
PollForUs::Application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get :confirm_email
  end


  resource :text_messages, :only => [] do 
    post :receive_text_message
  end

  resource :session, only: [:new, :create, :destroy] do
    get :sign_out
    get :show_email_form
    post :reset_email
    get :show_reset_password
    post :reset_password
    get :guest_login
  end

  resources :polls, only: [:index, :show, :create, :update, :destroy]
  resources :questions, only: [:create, :update, :destroy]
  resources :answers, only: [:create, :update, :destroy]

  root to: "sessions#new"
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :name, :user_id, :questions_attributes

  validates :name, :user, presence: true
  
  belongs_to :user, :inverse_of => :polls
  has_many :questions, :dependent => :destroy, :inverse_of => :poll
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:body].blank? }
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  layout "backbone"
  respond_to :json

  before_filter :require_login, :except => [:index, :show]

  def require_login
    redirect_to new_session_url unless current_user
  end

  def index
    if current_user
      #allows us to use @current_user in userRABL file
      @current_user = current_user
      @polls = Poll.includes(:questions => {:answers => :answer_choices}).where(:user_id => current_user.id)
    end

    if(@polls)
      respond_to do |format|
        format.html { render :index }
        format.json { render :indexRABL }
      end
    end
  end

  def create
    @poll = Poll.new(params[:poll])
    @poll.user_id = current_user.id
    if @poll.save
      render :showRABL
    else
      render 422
    end
  end

  def show
    @poll = Poll.find(params[:id])
    if @poll
      render :showRABL
    else
      render 422
    end
  end

  def update
    @poll = Poll.find(params[:id])
    if @poll.update_attributes(params[:poll])
      render :showRABL
    else
      render 422
    end
  end

  def destroy
    puts "here in polls controller!"
    @poll = Poll.find(params[:id])
    if @poll
      @poll.destroy
    end
    render :showRABL
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/index.html.erb
<script type="application/json" id="polls-data">
  <%= (render(:file => 'polls/indexRABL.rabl')).html_safe %>
</script>
<script type="application/json" id="current-user-data">
  <%= (render(:file => 'layouts/userRABL.rabl')).html_safe %>
</script>
<div class="content container">
</div>

app/views/polls/new.html.erb
<h3>New Poll</h3>
<form action="<%= polls_url %>" method="POST">
  <label for="name">Name</label>
  <input type="text" name="poll[name]" id="name">
  <br>
  <a class="add-question btn btn-primary" href="#">Add Question</a>
  <div class="questions">
  </div>
  <br>
  <input type="submit" value="Create Poll!">
</form>
<script>
  $(document).ready(function() {
    $(".add-question").click(function() {
      event.preventDefault();
      addQuestion();
    });

    var addQuestion = function() {
      $(.question).append("<input type='text'>");
    }
  });
</script>