config/routes.rb
PollForUs::Application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get :confirm_email
  end


  resource :text_messages, :only => [] do 
    post :receive_text_message
  end

  resource :session, only: [:new, :create, :destroy] do
    get :sign_out
    get :show_email_form
    post :reset_email
    get :show_reset_password
    post :reset_password
    get :guest_login
  end

  resources :polls, only: [:index, :show, :create, :update, :destroy]
  resources :questions, only: [:create, :update, :destroy]
  resources :answers, only: [:create, :update, :destroy]

  root to: "sessions#new"
end

app/views/layouts/_flash.html.erb
<% if flash[:errors] %>
  <div class="alert alert-error">  
    <a class="close" data-dismiss="alert">×</a>  
    <% flash[:errors].each do |error| %>
      <h5> <%= error %> </h5>
    <% end %>
  </div>  
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-block">  
    <a class="close" data-dismiss="alert">×</a>  
    <% flash[:notice].each do |notice| %>
      <h5> <%= notice %> </h5>
    <% end %>
  </div> 
<% end %>

<% if flash[:successes] %>
  <div class="alert alert-success">  
  <a class="close" data-dismiss="alert">×</a>  
    <% flash[:successes].each do |success| %>
      <h5> <%= success %> </h5>
    <% end %>
  </div>  
<% end %>

app/views/layouts/_log_in.html.erb
<% if current_user %>
    <a href="<%= sign_out_session_url %>" class="btn btn-primary" style="margin-top:27px;">Sign Out</a>
<% else %>
    <a href="<%= new_session_url %>" class="btn btn-primary" style="margin-top:27px;">Sign In</a>
    <a href="<%= new_user_url %>" class="btn btn-primary" style="margin-top:27px;">Sign Up</a>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand logo" href="#"><img src="../pollforus_logo_smaller.png"></a>
      <div class="nav pull-right log-in-content">
        <%= render "/layouts/log_in" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>PollForUs</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "/layouts/navbar" %>
    <%= render "layouts/flash", flash: flash %>
    <%= yield %>
  </body>
</html>

app/views/layouts/backbone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>PollForUs</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script src="https://d3dy5gmtp8yhk7.cloudfront.net/2.1/pusher.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    // setting up pusher 
    var pusher = new Pusher('<%= Pusher.key %>');
    var channel = pusher.subscribe('all_poll_answers');
    channel.bind('updated', function(data) {
      var current_answer = PollForUs.allAnswers.get(data.answer_id);
      current_answer.set("user_answers", data.user_answers);
    });
  </script>
<%= csrf_meta_tags %>
</head>
<body>
  <%= render "/layouts/navbar" %>
  <%= render "layouts/flash", flash: flash %>

  <%= yield %>

  </body>
</html>